name: Migrate to prod (default)

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'The pull request number'
        required: true
        type: number

env:
  GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
  PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }} # Production or primary database
  PG_VERSION: '16'

jobs:
  run-on-main-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files changed in PR
        id: list_files
        run: |
          pr_number=${{ github.event.inputs.pr_number || github.event.pull_request.number }}
          changed_files=$(gh pr view $pr_number --json files --jq '.files[].path' | tr '\n' ' ')
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Show PR diff
        run: |
          pr_number=${{ github.event.inputs.pr_number || github.event.pull_request.number }}
          gh pr diff $pr_number

      - name: Install PostgreSQL
        run: |
          sudo apt update
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Echo file names
        run: |
          echo "Changed files in PR:"
          echo "${{ env.changed_files }}"
