name: Migrate to prod (merge)

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
  PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }} # Production or primary database
  PG_VERSION: '16'

jobs:
  run-on-main-merge:
    runs-on: ubuntu-latest

    steps:
      # - name: Install PostgreSQL
      #   run: |
      #     sudo apt update
      #     yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
      #     sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          # Fetch the latest state of the main branch
          git fetch origin main

      - name: Fetch base branch
        run: |
          # Fetch the latest state of the base branch (main)
          git fetch origin main
          git checkout main
          git pull origin main
          echo "Base branch updated"

      - name: Get latest commit SHA
        id: get_commit_sha
        run: |
          # Get the latest commit SHA from the push event
          latest_commit_sha=$(git rev-parse HEAD)
          echo "Latest Commit SHA: $latest_commit_sha"
          echo "latest_commit_sha=$latest_commit_sha" >> $GITHUB_ENV

      - name: Get base commit SHA
        id: get_base_commit_sha
        run: |
          # Get the base commit SHA for comparison
          base_commit_sha=$(git rev-parse origin/main)
          echo "Base Commit SHA: $base_commit_sha"
          echo "base_commit_sha=$base_commit_sha" >> $GITHUB_ENV

      # - name: Apply migrations
      #   run: |
      #     while IFS= read -r file; do
      #       # Check if the file exists
      #       if [ ! -f "$file" ]; then
      #         echo "$file does not exist"
      #         continue
      #       fi

      #       # Check if the file has a .sql extension
      #       if [[ "$file" != *.sql ]]; then
      #         echo "$file is not a SQL file"
      #         continue
      #       fi

      #       # Apply the SQL file
      #       echo "Processing $file"
      #       if ! /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/psql "${{ env.PROD_DATABASE_URL }}" < "$file"; then
      #         echo "Error applying $file"
      #         exit 1
      #       fi
      #     done < migration_files.txt
