name: Migrate to prod (merge)

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
  PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }} # Production or primary database
  PG_VERSION: '16'

jobs:
  run-on-main-merge:
    runs-on: ubuntu-latest

    steps:
      # - name: Install PostgreSQL
      #   run: |
      #     sudo apt update
      #     yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
      #     sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: |
          git fetch origin main
          echo "Fetched latest changes from main"

      - name: Get previous commit SHA
        id: get_previous_commit
        run: |
          previous_commit_sha=$(git rev-parse HEAD^)
          echo "Previous Commit SHA: $previous_commit_sha"
          echo "previous_commit_sha=$previous_commit_sha" >> $GITHUB_ENV

      - name: Get changed files
        run: |
          latest_commit_sha=$(git rev-parse HEAD)
          echo "Latest Commit SHA: $latest_commit_sha"

          git diff --name-only $previous_commit_sha $latest_commit_sha > migration_files.txt
          echo "Changed files:"
          cat migration_files.txt

      # - name: Apply migrations
      #   run: |
      #     while IFS= read -r file; do
      #       # Check if the file exists
      #       if [ ! -f "$file" ]; then
      #         echo "$file does not exist"
      #         continue
      #       fi

      #       # Check if the file has a .sql extension
      #       if [[ "$file" != *.sql ]]; then
      #         echo "$file is not a SQL file"
      #         continue
      #       fi

      #       # Apply the SQL file
      #       echo "Processing $file"
      #       if ! /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/psql "${{ env.PROD_DATABASE_URL }}" < "$file"; then
      #         echo "Error applying $file"
      #         exit 1
      #       fi
      #     done < migration_files.txt
