name: Migrate to prod (default)

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

env:
  PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }} # Production or primary database
  PG_VERSION: '16'

jobs:
  run-on-main-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history

      - name: Fetch base branch
        run: |
          git fetch origin main  # Ensure the base branch (main) is up-to-date

      - name: Debug information
        run: |
          # Display the current branch and status
          echo "Current branch:"
          git branch
          echo "Current status:"
          git status

          # Display the latest commits on the main branch and current branch
          echo "Latest commits on origin/main:"
          git log origin/main -n 5
          echo "Latest commits on current branch:"
          git log HEAD -n 5

      - name: Identify new migration files
        id: new_files
        run: |
          set -x  # Print each command before executing
          git diff --name-only origin/main...HEAD | grep '\.sql$' > new_migrations.txt || true
          echo "New migration files:"
          cat new_migrations.txt
